<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pernyataan extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Pernyataan_model');
        $this->load->library('form_validation');        
	    $this->load->library('datatables');
    }

    public function index()
    {
        $this->template->load('template','pernyataan/pernyataan_list');
    }

    public function json() {
        header('Content-Type: application/json');
        echo $this->Pernyataan_model->json();
    }
    
    public function create() 
    {
        $nama_foto = "ttd".time();
        $data = array(
            'button' => 'Create',
            'action' => site_url('pernyataan/create_action'),
            'nama_siswa' => set_value('nama_siswa'),
            'nik_siswa' => set_value('nik_siswa'),
            'kelas' => set_value('kelas'),
            'sekolah' => set_value('sekolah'),
            'alamat' => set_value('alamat'),
            'nama_ortu' => set_value('nama_ortu'),
            'nik_ortu' => set_value('nik_ortu'),
            'pekerjaan' => set_value('pekerjaan'),
            'images' => set_value($nama_foto),
        );
        $this->template->load('template','pernyataan/pernyataan_form', $data);
    }

    public function create_action() 
    {
        $this->_rules();
        $foto = $this->upload_foto();
        $nama_foto = "ttd".time();
        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
                'nama_siswa' => $this->input->post('nama_siswa', TRUE),
                'nik_siswa' => $this->input->post('nik_siswa',TRUE),
                'kelas' => $this->input->post('kelas',TRUE),
                'sekolah' => $this->input->post('sekolah',TRUE),
                'alamat' => $this->input->post('alamat',TRUE),
                'nama_ortu' => $this->input->post('nama_ortu',TRUE),
                'nik_ortu' => $this->input->post('nik_ortu',TRUE),
                'pekerjaan' => $this->input->post('pekerjaan',TRUE),
                'images' => $foto['file_name'],
                'dtm_crt' => date("Y-m-d H:i:s",  time()),
                'dtm_upd' => date("Y-m-d H:i:s",  time()),
            );
            $this->Pernyataan_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('pernyataan'));
        }
    }

    public function _rules() 
    {
        $this->form_validation->set_rules('nama_siswa', 'Nama Siswa', 'trim|required');
        $this->form_validation->set_rules('nik_siswa', 'NIK Siswa', 'trim|required');
        $this->form_validation->set_rules('kelas', 'Kelas', 'trim|required');
        $this->form_validation->set_rules('sekolah', 'Sekolah', 'trim|required');
        $this->form_validation->set_rules('alamat', 'Alamat', 'trim|required');
        $this->form_validation->set_rules('nama_ortu', 'Nama Orang Tua', 'trim|required');
        $this->form_validation->set_rules('nik_ortu', 'NIK Orang Tua', 'trim|required');
        $this->form_validation->set_rules('pekerjaan', 'Pekerjaan', 'trim|required');
        $this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

    public function cetak($id){
        $cetak = $this->Pernyataan_model->get_by_id($id);
        $this->data['nama_ortu'] = $cetak->nama_ortu;
        $this->data['nik_ortu'] = $cetak->nik_ortu;
        $this->data['pekerjaan'] = $cetak->pekerjaan;
        $this->data['alamat'] = $cetak->alamat;
        $this->data['nama_siswa'] = $cetak->nama_siswa;
        $this->data['nik_siswa'] = $cetak->nik_siswa;
        $this->data['kelas'] = $cetak->kelas;
        $this->data['sekolah'] = $cetak->sekolah;
        $this->data['ttd'] = $cetak->images;
        $this->load->view('pernyataan/pernyataan_cetak', $this->data);
    }

    function upload_foto(){
        $config['upload_path']          = './assets/ttd';
        $config['allowed_types']        = 'gif|jpg|png';
        //$config['max_size']             = 100;
        //$config['max_width']            = 1024;
        //$config['max_height']           = 768;
        $this->load->library('upload', $config);
        $this->upload->do_upload('images');
        return $this->upload->data();
    }


}

/* End of file Kelolamenu.php */
/* Location: ./application/controllers/Kelolamenu.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-10-04 10:50:27 */
/* http://harviacode.com */